Repository XIKDEV/x-nom-035-backend, pull requests merged in 2024-10, with the labels that each got.

#81 refactor: Update CatalogsService to include staticCatalog method
  src/catalogs/catalogs/services/catalogs.service.ts
Labels: enhancement

#93 92 revisar bandera status en queries
  .vscode/settings.json
  src/config/common/utils/index.ts
  src/config/common/utils/prisma.util.ts
  src/config/database/constants/index.ts
  src/config/database/index.ts
  src/config/database/services/prisma.service.ts
  src/modules/users/helpers/user.prisma.helper.service.ts
Labels: enhancement, refactor

#94 feat(contracts): :sparkles: create module and service to create contr…
  .vscode/settings.json
  eslint.config.mjs
  prisma/schema.prisma
  src/app.module.ts
  src/catalogs/catalogs/index.ts
  src/catalogs/index.ts
  src/catalogs/type-test/helpers/type-test.prisma.helper.service.ts
  src/catalogs/type-test/index.ts
  src/catalogs/type-test/messages/index.ts
  src/catalogs/type-test/services/index.ts
  src/catalogs/type-test/services/type-test.prisma.helper.service.ts
  src/catalogs/type-test/type-test.module.ts
  src/config/dto-validators/constants/index.ts
  src/modules/contracts/contracts.module.ts
  src/modules/contracts/controllers/contracts.controller.ts
  src/modules/contracts/controllers/index.ts
  src/modules/contracts/dtos/create-contracts.dto.ts
  src/modules/contracts/dtos/index.ts
  src/modules/contracts/index.ts
  src/modules/contracts/interfaces/index.ts
  src/modules/contracts/services/contracts.prisma.service.ts
  src/modules/contracts/services/contracts.service.ts
  src/modules/contracts/services/index.ts
  src/modules/index.ts
  src/modules/users/helpers/user.prisma.helper.service.ts
  src/modules/users/services/user.service.ts
  src/modules/users/user.module.ts
  src/providers/firebase/services/firebase.service.ts
  src/providers/index.ts
  src/providers/nodemailer/index.ts
Labels: documentation, enhancement, refactor

#97 Refactor prisma schema and add camel case formatting
  README.md
Labels: documentation

#98 95 crear servicios faltantes para contratos
  src/config/common/dto/id-enterprise-find-all.dto.ts
  src/config/common/dto/index.ts
  src/modules/contracts/controllers/contracts.controller.ts
  src/modules/contracts/interfaces/index.ts
  src/modules/contracts/messages/index.ts
  src/modules/contracts/services/contracts.prisma.service.ts
  src/modules/contracts/services/contracts.service.ts
  src/modules/enterprises/controllers/enterprises.controller.ts
  src/modules/enterprises/services/enterprises.service.ts
Labels: documentation, enhancement, refactor

#99 Update dependencies in package.json
  package.json
Labels: update

#105 Update dependencies and add Swagger UI customization
  package.json
  public/swagger.css
  src/main.ts
  src/modules/contracts/services/contracts.service.ts
Labels: enhancement

#102 101 catalogo de preguntas e insercion en bd
  .vscode/settings.json
  prisma/schema.prisma
  src/app.module.ts
  src/catalogs/catalogs/catalogs.module.ts
  src/catalogs/catalogs/services/catalogs.service.ts
  src/catalogs/index.ts
  src/catalogs/sections/index.ts
  src/catalogs/sections/interfaces/index.ts
  src/catalogs/sections/sections.module.ts
  src/catalogs/sections/services/index.ts
  src/catalogs/sections/services/sections.prisma.service.ts
Labels: enhancement, refactor, DB

#103 29 crear roles
  src/catalogs/roles/controllers/index.ts
  src/catalogs/roles/controllers/roles.controller.ts
  src/catalogs/roles/dto/create-roles.dto.ts
  src/catalogs/roles/dto/index.ts
  src/catalogs/roles/helpers/roles.prisma.helper.service.ts
  src/catalogs/roles/index.ts
  src/catalogs/roles/interfaces/index.ts
  src/catalogs/roles/messages/index.ts
  src/catalogs/roles/roles.module.ts
  src/catalogs/roles/services/index.ts
  src/catalogs/roles/services/roles.services.ts
  src/config/dto-validators/constants/index.ts
  src/modules/enterprises/enterprises.module.ts
  src/modules/users/user.module.ts
Labels: enhancement
